// Client Remote descriptors for the skill-library manager.
//
// The Client Web page mounts this contribution to build the typed
// `ctx.remote.skillManager` namespace. Each descriptor mirrors one `@Remote`
// export declared by the Host service (index.js):
//
//   endpoint  = `<namespace>/<method>`   → `skillManager/<method>`
//   wire name = the Host method's own parameter name (Host runs in SRC mode,
//               deriving wire names from the method signature), so `request`
//               arguments arrive under the `request` key.
//
// Every codec is `mode: "strict"` (the Client's `validateContribution`
// requires it) and every `create()` returns a permissive pass-through schema.
// The optional `decode` is intentionally omitted, so the Client forwards the
// Host's JSON result unchanged and never rejects a valid response on a schema
// mismatch. The Host's own `@Remote` markers (not these descriptors) drive the
// authoritative dispatch, so this file only has to satisfy the Client mount
// contract.
//
// Generated by hand to match the Host `@Remote` surface; keep it in sync with
// the marker map at the bottom of index.js.

const PACKAGE = '@local/skill-manager'
const NAMESPACE = 'skillManager'

/** Permissive stand-in for a generated zod schema. The Client never parses with it (no decode). */
const passthrough = () => ({
	parse: (value) => value,
	safeParse: (value) => ({ success: true, data: value }),
})

/** A strict codec carrying only what the mount contract checks: mode, typeSymbol, create(). */
const codec = (typeSymbol) => ({ mode: 'strict', typeSymbol, create: passthrough })

/** Parameter descriptor for the single `request` object argument. */
const requestParam = (method) => ({
	name: 'request',
	wire: 'request',
	source: 'json',
	codec: codec(`${PACKAGE}#${method}:request`),
})

/** Result codec for a method whose return value is forwarded unchanged. */
const result = (method) => codec(`${PACKAGE}#${method}:result`)

function descriptor(method, { params = true, cancel = true } = {}) {
	const entry = {
		id: `${PACKAGE}#${NAMESPACE}/${method}`,
		service: NAMESPACE,
		namespace: NAMESPACE,
		method,
		invocation: { kind: 'direct' },
		parameters: params ? [requestParam(method)] : [],
		result: result(method),
	}
	if (cancel) entry.cancellation = { parameter: 'signal' }
	return entry
}

export const TYPERT_REMOTE = {
	package: PACKAGE,
	descriptors: [
		descriptor('roots', { params: false }),
		descriptor('scan', { params: false }),
		descriptor('refresh', { params: false }),
		descriptor('updateCategory'),
		descriptor('createCategory'),
		descriptor('renameCategory'),
		descriptor('deleteCategory'),
		descriptor('setAlias'),
		descriptor('setFavorite'),
		descriptor('configure'),
		descriptor('deleteSkill'),
		descriptor('trashList', { params: false }),
		descriptor('restore'),
		descriptor('purge'),
		descriptor('validateSource'),
		descriptor('installLocal'),
		descriptor('installGit'),
		descriptor('revealPath'),
		descriptor('exportCatalog'),
		descriptor('skillDetail'),
	],
}

export default TYPERT_REMOTE
